// <auto-generated />
using LocalDevelop.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalDevelop.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20200103094409_ini")]
    partial class ini
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LocalDevelop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10,
                            Detail = "ABCD",
                            Name = "Dell Notebook XPS 13",
                            Price = 55000.0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 5,
                            Detail = "ABCD",
                            Name = "Lenovo X230",
                            Price = 32000.0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 3,
                            Detail = "ABCD",
                            Name = "Microsoft Surface Pro 7",
                            Price = 60000.0
                        },
                        new
                        {
                            Id = 4,
                            Amount = 10,
                            Detail = "ABCD",
                            Name = "Apple Macbook Pro 2020",
                            Price = 45000.0
                        },
                        new
                        {
                            Id = 10,
                            Amount = 1,
                            Detail = "ABCD",
                            Name = "Apple Mac Pro",
                            Price = 100000.0
                        },
                        new
                        {
                            Id = 11,
                            Amount = 20,
                            Detail = "ABCD",
                            Name = "Apple Ipad 2018",
                            Price = 15000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
